<?php
require_once '../../../includes/auth.php';
require_once '../../../config/database.php';

// Permission check
if (!hasPermission('quotations.manage')) {
    die("You don't have permission to access this page");
}

// Get quotation ID
$quotation_id = $_GET['id'] ?? 0;

// Fetch quotation details
$stmt = $pdo->prepare("
    SELECT q.*, c.name AS customer_name, c.tax_number, c.address,
           cc.name AS contact_name, cc.phone AS contact_phone,
           u.name AS created_by_name
    FROM quotations q
    JOIN customers c ON q.customer_id = c.id
    JOIN customer_contacts cc ON q.contact_id = cc.id
    JOIN users u ON q.created_by = u.id
    WHERE q.id = ?
");
$stmt->execute([$quotation_id]);
$quotation = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$quotation) {
    die("Quotation not found");
}

// Fetch quotation items
$stmt = $pdo->prepare("
    SELECT qi.*, p.name AS product_name, p.sku, p.barcode, p.type
    FROM quotation_items qi
    JOIN products p ON qi.product_id = p.id
    WHERE qi.quotation_id = ?
");
$stmt->execute([$quotation_id]);
$items = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Check permissions for price visibility
$canViewFinalPrices = canViewProductPrice('final');

// Clean output buffer and suppress warnings before PDF generation
if (ob_get_length()) ob_clean();
error_reporting(E_ERROR | E_PARSE);

// Include TCPDF library
require_once '../../../tcpdf/tcpdf.php';

// Create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Your Company Name');
$pdf->SetTitle('Quotation #' . $quotation['id']);
$pdf->SetSubject('Quotation');

// Set margins
$pdf->SetMargins(15, 15, 15);
$pdf->SetHeaderMargin(10);
$pdf->SetFooterMargin(10);
$primaryFont = 'aealarabiya';

// Add a page
$pdf->AddPage();

// Quotation title
$pdf->SetFont($primaryFont, 'B', 16);
$pdf->Ln(10);
$pdf->Cell(0, 10, 'QUOTATION', 0, 1, 'C');
$pdf->Ln(5);

// Quotation details
$pdf->SetFont($primaryFont, '', 10);
$pdf->Cell(50, 5, 'Quotation Number:', 0, 0);
$pdf->Cell(0, 5, $quotation['id'], 0, 1);
$pdf->Cell(50, 5, 'Quotation Date:', 0, 0);
$pdf->Cell(0, 5, date('F j, Y', strtotime($quotation['quotation_date'])), 0, 1);
$pdf->Cell(50, 5, 'Expiry Date:', 0, 0);
$pdf->Cell(0, 5, date('F j, Y', strtotime($quotation['expiry_date'])), 0, 1);
$pdf->Cell(50, 5, 'Customer:', 0, 0);
$pdf->Cell(0, 5, $quotation['customer_name'], 0, 1);
$pdf->Cell(50, 5, 'Tax Number:', 0, 0);
$pdf->Cell(0, 5, $quotation['tax_number'] ?? '', 0, 1);
$pdf->Cell(50, 5, 'Address:', 0, 0);
$pdf->MultiCell(0, 5, $quotation['address'] ?? '', 0, 1);
$pdf->Cell(50, 5, 'Contact:', 0, 0);
$pdf->Cell(0, 5, $quotation['contact_name'] . ' (' . $quotation['contact_phone'] . ')', 0, 1);
$pdf->Cell(50, 5, 'Status:', 0, 0);
$statusLabels = [
    'draft' => 'Draft',
    'sent' => 'Sent',
    'accepted' => 'Accepted',
    'rejected' => 'Rejected',
    'converted' => 'Converted'
];
$pdf->Cell(0, 5, $statusLabels[$quotation['status']] ?? ucfirst($quotation['status']), 0, 1);
$pdf->Ln(5);

// Items table
$pdf->SetFont($primaryFont, 'B', 10);
$pdf->Cell(15, 7, '#', 1, 0, 'C');
$pdf->Cell(75, 7, 'Product', 1, 0);
$pdf->Cell(20, 7, 'Qty', 1, 0, 'C');
$pdf->Cell(30, 7, 'Unit Price', 1, 0, 'R');
$pdf->Cell(30, 7, 'Total', 1, 1, 'R');

$pdf->SetFont($primaryFont, '', 10);
$counter = 1;
foreach ($items as $item) {
    $pdf->Cell(15, 7, $counter++, 1, 0, 'C');
    $pdf->Cell(75, 7, $item['product_name'], 1, 0);
    $pdf->Cell(20, 7, $item['quantity'], 1, 0, 'C');
    if (canViewProductPrice($item['type'])) {
        $pdf->Cell(30, 7, number_format($item['unit_price'], 2), 1, 0, 'R');
        $pdf->Cell(30, 7, number_format($item['total_price'], 2), 1, 1, 'R');
    } else {
        $pdf->Cell(30, 7, 'Hidden', 1, 0, 'R');
        $pdf->Cell(30, 7, 'Hidden', 1, 1, 'R');
    }
}

// Summary
$pdf->Ln(10);
$pdf->SetFont($primaryFont, 'B', 10);
$pdf->Cell(140, 7, 'Total:', 1, 0, 'R');
if ($canViewFinalPrices) {
    $pdf->Cell(30, 7, number_format($quotation['total_amount'], 2), 1, 1, 'R');
} else {
    $pdf->Cell(30, 7, 'Hidden', 1, 1, 'R');
}

// Notes
if (!empty($quotation['notes'])) {
    $pdf->Ln(10);
    $pdf->SetFont($primaryFont, 'I', 9);
    $pdf->MultiCell(0, 5, 'Notes: ' . $quotation['notes']);
}

// Footer
$pdf->SetY(-30);
$pdf->SetFont($primaryFont, 'I', 8);
$pdf->Cell(0, 5, 'Generated by ' . $quotation['created_by_name'] . ' on ' . date('Y-m-d H:i:s'), 0, 1);
$pdf->Cell(0, 5, 'This quotation is valid until ' . date('F j, Y', strtotime($quotation['expiry_date'])), 0, 1, 'C');

// Output PDF
$pdf->Output('quotation_' . $quotation['id'] . '.pdf', 'I');
?>